# Generated by Django 4.2.29 on 2026-03-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_create_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@nomadsocks.com", max_length=254),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+976 9999 9999", max_length=50
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="Ulaanbaatar, Mongolia", max_length=200
                    ),
                ),
                (
                    "address_mn",
                    models.CharField(
                        blank=True, default="Улаанбаатар, Монгол", max_length=200
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "tagline",
                    models.CharField(
                        default="Quality socks from Mongolia", max_length=200
                    ),
                ),
                (
                    "tagline_mn",
                    models.CharField(default="Монголын чанартай оймс", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
