# Generated by Django 4.2.29 on 2026-03-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "Ерөнхий асуулт"),
                            ("order", "Захиалга өгөх"),
                            ("shipping", "Хүргэлтийн асуулт"),
                            ("wholesale", "Бөөний худалдааны асуулт"),
                            ("other", "Бусад"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200, verbose_name="Нэр")),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Имэйл"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Утасны дугаар"),
                ),
                ("shipping_address", models.TextField(verbose_name="Хүргэлтийн хаяг")),
                (
                    "shipping_city",
                    models.CharField(
                        default="Улаанбаатар", max_length=100, verbose_name="Хот"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Хүлээгдэж буй"),
                            ("confirmed", "Баталгаажсан"),
                            ("paid", "Төлбөр хийгдсэн"),
                            ("shipped", "Илгээгдсэн"),
                            ("delivered", "Хүргэгдсэн"),
                            ("cancelled", "Цуцлагдсан"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("qpay", "QPay"),
                            ("socialpay", "SocialPay"),
                            ("bank_transfer", "Банкны шилжүүлэг"),
                            ("cash", "Бэлэн мөнгө"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="QPay/SocialPay transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Тэмдэглэл")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=5)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
