# Generated by Django 4.2.29 on 2026-03-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "name_mn",
                    models.CharField(max_length=100, verbose_name="Нэр (Монгол)"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"verbose_name_plural": "Categories", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "name_mn",
                    models.CharField(max_length=200, verbose_name="Нэр (Монгол)"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("description_mn", models.TextField(verbose_name="Тайлбар (Монгол)")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, help_text="Үнэ (₮)", max_digits=10
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "material",
                    models.CharField(
                        default="80% хөвөн, 17% полиэстер, 3% эластан", max_length=200
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={"ordering": ["-is_featured", "-created_at"],},
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=200)),
                (
                    "feature_mn",
                    models.CharField(max_length=200, verbose_name="Онцлог (Монгол)"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
