# Generated by Django 4.2.29 on 2026-03-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (use this instead of upload)",
                null=True,
            ),
        ),
    ]
